### ISSUE TITLE
Landing page join our API Newsletter not working

### ISSUE THREAD

**Issue by OlukaDenis** [NovelCOVID/API#581]
I have checked the newsletter submission for both https://corona.lmao.ninja/ and https://disease.sh/, the newsletter submission isn't working.
Watch this [video](https://www.loom.com/share/3398ea027b2a4307bb4fabc01a122799) I recorded the response.
Thanks

**Comment by ebwinters** [comment]
ok weird. go to it now, in a new session, and try again

**Comment by puf17640** [comment]
looking at this
any console error?

**Comment by puf17640** [comment]
![image](https://user-images.githubusercontent.com/17516174/80069732-27c85e80-8542-11ea-9f9b-26e15868c0f6.png)

**Comment by EliteDaMyth** [comment]
Seems like an csrf token issue
```
ForbiddenError: invalid csrf token
    at csrf (/opt/covid-api/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/opt/covid-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/covid-api/node_modules/express/lib/router/route.js:137:13)
    at urlencodedParser (/opt/covid-api/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/opt/covid-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/covid-api/node_modules/express/lib/router/route.js:137:13)
    at /opt/covid-api/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/opt/covid-api/node_modules/raw-body/index.js:224:16)
    at done (/opt/covid-api/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/opt/covid-api/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:317:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1215:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by puf17640** [comment]
yeah but it works for me now... can you all try too?

**Comment by OlukaDenis** [comment]
Great it works now.
![Screenshot from 2020-04-23 12-00-37](https://user-images.githubusercontent.com/37341054/80080338-260a9500-855a-11ea-885f-041110c560df.png)

But one more thing, I think it would be perfect to clear up the input text when it is a success. How do you think?

**Comment by EliteDaMyth** [comment]
@OlukaDenis you can open a pull request maybe? also if further help is not needed please close this issue :)

**Comment by OlukaDenis** [comment]
Okay lemme jump to it
