### ISSUE TITLE
Error fetching 

### ISSUE THREAD

**Issue by skavinvarnan** [NovelCOVID/API#594]
JHU File not found at this URL https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/04-24-2020.csv

This happens because CSV is not generated yet for that day. Can this error be handled more gracefully?

Error
```
{
  message: '[2020-04-25T06:46:37.768Z]: Error: Requesting JHULocations failed!',
  error: 'Request failed with status code 404',
  stack: 'Error: Request failed with status code 404\n' +
    '    at createError (/Users/skavinvarnan/Projects/Node/NovelAPI/node_modules/axios/lib/core/createError.js:16:15)\n' +
    '    at settle (/Users/skavinvarnan/Projects/Node/NovelAPI/node_modules/axios/lib/core/settle.js:17:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/Users/skavinvarnan/Projects/Node/NovelAPI/node_modules/axios/lib/adapters/http.js:236:11)\n' +
    '    at IncomingMessage.emit (events.js:215:7)\n' +
    '    at endReadableNT (_stream_readable.js:1183:12)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:80:21)'
}
(node:91365) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at Object.jhudataV2 (/NovelAPI/scrapers/jhuLocations.js:29:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```

**Comment by puf17640** [comment]
it could be handled more gracefully, yes

i will make it return after logging the error
